import type { ProductCardData, Artisan, Testimonial, Category } from './types'

// ============================================================
// Mock / Seed Data for development without Supabase
// ============================================================

export const CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Banarasi',
    slug: 'banarasi',
    description: 'Opulent Banarasi silk sarees woven with pure gold and silver zari threads in the ancient city of Varanasi.',
    image_url: '/images/sarees/banarasi-red.png',
    parent_id: null,
    sort_order: 1,
  },
  {
    id: '2',
    name: 'Kanjivaram',
    slug: 'kanjivaram',
    description: 'The queen of silks — Kanjivaram sarees from Tamil Nadu, renowned for their luster and temple-inspired motifs.',
    image_url: '/images/sarees/kanjivaram-purple.png',
    parent_id: null,
    sort_order: 2,
  },
  {
    id: '3',
    name: 'Chanderi',
    slug: 'chanderi',
    description: 'Lightweight, sheer elegance from Madhya Pradesh — Chanderi sarees with their signature gossamer texture.',
    image_url: '/images/sarees/chanderi-green.png',
    parent_id: null,
    sort_order: 3,
  },
  {
    id: '4',
    name: 'Organza',
    slug: 'organza',
    description: 'Ethereal organza sarees with delicate embroidery, perfect for contemporary celebrations.',
    image_url: '/images/sarees/festive-orange.png',
    parent_id: null,
    sort_order: 4,
  },
  {
    id: '5',
    name: 'Printed',
    slug: 'printed',
    description: 'Contemporary printed sarees blending traditional motifs with modern artistry.',
    image_url: '/images/sarees/silk-blue.png',
    parent_id: null,
    sort_order: 5,
  },
  {
    id: '6',
    name: 'Embroidered',
    slug: 'embroidered',
    description: 'Exquisitely hand-embroidered sarees featuring intricate needlework traditions.',
    image_url: 'https://images.unsplash.com/photo-1583391733981-8b530abef6c0?w=1200&q=90',
    parent_id: null,
    sort_order: 6,
  },
  {
    id: '7',
    name: 'Custom',
    slug: 'custom',
    description: 'Design your dream saree with our master artisans. Custom creations tailored to your vision.',
    image_url: '/images/sarees/ivory-wedding.png',
    parent_id: null,
    sort_order: 7,
  },
]

export const PRODUCTS: ProductCardData[] = [
  {
    id: '1',
    name: 'Gulabi Banarasi Silk',
    slug: 'gulabi-banarasi-silk',
    fabric: 'Pure Silk',
    category_name: 'Banarasi',
    image_url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=90&fit=crop',
    price: 8499,
    compare_price: 10999,
    rating: 4.8,
    review_count: 24,
    badge: 'NEW',
    is_customizable: false,
    colors: [
      { name: 'Gulabi Pink', hex: '#E8A0BF' },
      { name: 'Royal Gold', hex: '#C9A84C' },
    ],
  },
  {
    id: '2',
    name: 'Royal Kanjivaram Gold',
    slug: 'royal-kanjivaram-gold',
    fabric: 'Pure Kanjivaram Silk',
    category_name: 'Kanjivaram',
    image_url: 'https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg?w=800&q=90',
    price: 14999,
    compare_price: 18000,
    rating: 4.9,
    review_count: 42,
    badge: 'LIMITED',
    is_customizable: false,
    colors: [
      { name: 'Royal Gold', hex: '#C9A84C' },
      { name: 'Deep Burgundy', hex: '#8B2635' },
    ],
  },
  {
    id: '3',
    name: 'Pearl Chanderi Tissue',
    slug: 'pearl-chanderi-tissue',
    fabric: 'Chanderi Tissue',
    category_name: 'Chanderi',
    image_url: 'https://images.unsplash.com/photo-1614886137526-e0aee5e0889b?w=800&q=90',
    price: 5499,
    compare_price: null,
    rating: 4.6,
    review_count: 18,
    badge: 'NEW',
    is_customizable: false,
    colors: [
      { name: 'Pearl White', hex: '#F5F0E8' },
      { name: 'Soft Gold', hex: '#E8D08A' },
    ],
  },
  {
    id: '4',
    name: 'Ivory Organza Dream',
    slug: 'ivory-organza-dream',
    fabric: 'Pure Organza',
    category_name: 'Organza',
    image_url: 'https://images.pexels.com/photos/3641056/pexels-photo-3641056.jpeg?w=800&q=90',
    price: 6999,
    compare_price: 8500,
    rating: 4.7,
    review_count: 31,
    badge: 'SALE',
    is_customizable: false,
    colors: [
      { name: 'Ivory', hex: '#FAF7F2' },
      { name: 'Champagne', hex: '#F7E7CE' },
    ],
  },
  {
    id: '5',
    name: 'Crimson Zari Brocade',
    slug: 'crimson-zari-brocade',
    fabric: 'Pure Silk',
    category_name: 'Banarasi',
    image_url: 'https://images.pexels.com/photos/8838890/pexels-photo-8838890.jpeg?w=800&q=90',
    price: 11999,
    compare_price: null,
    rating: 4.8,
    review_count: 15,
    badge: 'NEW',
    is_customizable: false,
    colors: [
      { name: 'Crimson Red', hex: '#DC143C' },
      { name: 'Gold', hex: '#C9A84C' },
    ],
  },
  {
    id: '6',
    name: 'Mango Temple Kanjivaram',
    slug: 'mango-temple-kanjivaram',
    fabric: 'Pure Kanjivaram Silk',
    category_name: 'Kanjivaram',
    image_url: 'https://images.pexels.com/photos/6712375/pexels-photo-6712375.jpeg?w=800&q=90',
    price: 17500,
    compare_price: 22000,
    rating: 5.0,
    review_count: 38,
    badge: 'LIMITED',
    is_customizable: false,
    colors: [
      { name: 'Mango Yellow', hex: '#FF8243' },
      { name: 'Temple Gold', hex: '#C9A84C' },
    ],
  },
  {
    id: '7',
    name: 'Pastel Chanderi Floral',
    slug: 'pastel-chanderi-floral',
    fabric: 'Chanderi Cotton Silk',
    category_name: 'Chanderi',
    image_url: 'https://images.pexels.com/photos/7260251/pexels-photo-7260251.jpeg?w=800&q=90',
    price: 4299,
    compare_price: 5500,
    rating: 4.5,
    review_count: 22,
    badge: 'SALE',
    is_customizable: false,
    colors: [
      { name: 'Pastel Pink', hex: '#FFD1DC' },
      { name: 'Mint Green', hex: '#98FB98' },
    ],
  },
  {
    id: '8',
    name: 'Midnight Blue Embroidered',
    slug: 'midnight-blue-embroidered',
    fabric: 'Georgette',
    category_name: 'Embroidered',
    image_url: 'https://images.pexels.com/photos/7260544/pexels-photo-7260544.jpeg?w=800&q=90',
    price: 9999,
    compare_price: 12500,
    rating: 4.8,
    review_count: 27,
    badge: 'NEW',
    is_customizable: false,
    colors: [
      { name: 'Midnight Blue', hex: '#191970' },
      { name: 'Silver', hex: '#C0C0C0' },
    ],
  },
  {
    id: '9',
    name: 'Blush Georgette Printed',
    slug: 'blush-georgette-printed',
    fabric: 'Georgette',
    category_name: 'Printed',
    image_url: 'https://images.pexels.com/photos/7691106/pexels-photo-7691106.jpeg?w=800&q=90',
    price: 3299,
    compare_price: null,
    rating: 4.3,
    review_count: 14,
    badge: null,
    is_customizable: false,
    colors: [
      { name: 'Blush Pink', hex: '#F5EDE3' },
      { name: 'Rose', hex: '#FF6B6B' },
    ],
  },
  {
    id: '10',
    name: 'Golden Temple Silk',
    slug: 'golden-temple-silk',
    fabric: 'Pure Kanjivaram Silk',
    category_name: 'Kanjivaram',
    image_url: 'https://images.pexels.com/photos/6231819/pexels-photo-6231819.jpeg?w=800&q=90',
    price: 21000,
    compare_price: 26000,
    rating: 5.0,
    review_count: 56,
    badge: 'LIMITED',
    is_customizable: false,
    colors: [
      { name: 'Temple Gold', hex: '#C9A84C' },
      { name: 'Deep Maroon', hex: '#800020' },
    ],
  },
  {
    id: '11',
    name: 'Aqua Organza Mirror Work',
    slug: 'aqua-organza-mirror-work',
    fabric: 'Pure Organza',
    category_name: 'Organza',
    image_url: 'https://images.pexels.com/photos/6765164/pexels-photo-6765164.jpeg?w=800&q=90',
    price: 7499,
    compare_price: 9000,
    rating: 4.6,
    review_count: 19,
    badge: 'SALE',
    is_customizable: false,
    colors: [
      { name: 'Aqua Blue', hex: '#7FDBFF' },
      { name: 'Silver', hex: '#C0C0C0' },
    ],
  },
  {
    id: '12',
    name: 'Rust Ikkat Pochampally',
    slug: 'rust-ikkat-pochampally',
    fabric: 'Cotton Silk',
    category_name: 'Printed',
    image_url: 'https://images.pexels.com/photos/6712376/pexels-photo-6712376.jpeg?w=800&q=90',
    price: 6200,
    compare_price: null,
    rating: 4.4,
    review_count: 11,
    badge: 'NEW',
    is_customizable: false,
    colors: [
      { name: 'Rust Orange', hex: '#B7410E' },
      { name: 'Indigo', hex: '#4B0082' },
    ],
  },
  {
    id: '13',
    name: 'Bridal Red Zari Kanjivaram',
    slug: 'bridal-red-zari-kanjivaram',
    fabric: 'Pure Kanjivaram Silk',
    category_name: 'Kanjivaram',
    image_url: 'https://images.pexels.com/photos/7260626/pexels-photo-7260626.jpeg?w=800&q=90',
    price: 32000,
    compare_price: 40000,
    rating: 5.0,
    review_count: 67,
    badge: 'LIMITED',
    is_customizable: false,
    colors: [
      { name: 'Bridal Red', hex: '#C41E3A' },
      { name: 'Pure Gold', hex: '#C9A84C' },
    ],
  },
  {
    id: '14',
    name: 'Sage Green Chanderi Silk',
    slug: 'sage-green-chanderi-silk',
    fabric: 'Chanderi Silk',
    category_name: 'Chanderi',
    image_url: 'https://images.unsplash.com/photo-1614886137526-e0aee5e0889b?w=800&q=90',
    price: 5799,
    compare_price: null,
    rating: 4.5,
    review_count: 16,
    badge: null,
    is_customizable: false,
    colors: [
      { name: 'Sage Green', hex: '#87AE73' },
      { name: 'Gold', hex: '#C9A84C' },
    ],
  },
  {
    id: '15',
    name: 'Navy Banarasi Tanchoi',
    slug: 'navy-banarasi-tanchoi',
    fabric: 'Pure Silk',
    category_name: 'Banarasi',
    image_url: 'https://images.pexels.com/photos/8839089/pexels-photo-8839089.jpeg?w=800&q=90',
    price: 13500,
    compare_price: 16000,
    rating: 4.7,
    review_count: 29,
    badge: 'SALE',
    is_customizable: false,
    colors: [
      { name: 'Navy Blue', hex: '#000080' },
      { name: 'Antique Gold', hex: '#CFB53B' },
    ],
  },
  {
    id: '16',
    name: 'Peach Organza Sequin',
    slug: 'peach-organza-sequin',
    fabric: 'Organza',
    category_name: 'Embroidered',
    image_url: 'https://images.pexels.com/photos/6765028/pexels-photo-6765028.jpeg?w=800&q=90',
    price: 8200,
    compare_price: 10000,
    rating: 4.6,
    review_count: 21,
    badge: 'NEW',
    is_customizable: false,
    colors: [
      { name: 'Peach', hex: '#FFDAB9' },
      { name: 'Rose Gold', hex: '#B76E79' },
    ],
  },
  {
    id: '17',
    name: 'Indigo Block Print Cotton',
    slug: 'indigo-block-print-cotton',
    fabric: 'Pure Cotton',
    category_name: 'Printed',
    image_url: 'https://images.pexels.com/photos/6712374/pexels-photo-6712374.jpeg?w=800&q=90',
    price: 2899,
    compare_price: null,
    rating: 4.2,
    review_count: 33,
    badge: null,
    is_customizable: false,
    colors: [
      { name: 'Indigo', hex: '#4B0082' },
      { name: 'Natural White', hex: '#FAEBD7' },
    ],
  },
  {
    id: '18',
    name: 'Emerald Paithani Silk',
    slug: 'emerald-paithani-silk',
    fabric: 'Pure Silk',
    category_name: 'Kanjivaram',
    image_url: 'https://images.pexels.com/photos/6231836/pexels-photo-6231836.jpeg?w=800&q=90',
    price: 24500,
    compare_price: 30000,
    rating: 4.9,
    review_count: 44,
    badge: 'LIMITED',
    is_customizable: false,
    colors: [
      { name: 'Emerald Green', hex: '#50C878' },
      { name: 'Gold', hex: '#C9A84C' },
    ],
  },
  {
    id: '19',
    name: 'Off-White Linen Handloom',
    slug: 'off-white-linen-handloom',
    fabric: 'Pure Linen',
    category_name: 'Chanderi',
    image_url: 'https://images.pexels.com/photos/7260249/pexels-photo-7260249.jpeg?w=800&q=90',
    price: 3599,
    compare_price: null,
    rating: 4.4,
    review_count: 12,
    badge: null,
    is_customizable: false,
    colors: [
      { name: 'Off-White', hex: '#FAF0E6' },
      { name: 'Natural', hex: '#C9B18C' },
    ],
  },
  {
    id: '20',
    name: 'Custom Bridal Creation',
    slug: 'custom-bridal-creation',
    fabric: 'Custom Selection',
    category_name: 'Custom',
    image_url: 'https://images.unsplash.com/photo-1609748340878-bc0f02e2b98c?w=800&q=90',
    price: 45000,
    compare_price: null,
    rating: 5.0,
    review_count: 89,
    badge: 'CUSTOMIZABLE',
    is_customizable: true,
    colors: [
      { name: 'As per choice', hex: '#C9A84C' },
    ],
  },
]

export const ARTISANS: Artisan[] = [
  {
    id: '1',
    name: 'Ramnath Vishwakarma',
    region: 'Varanasi, Uttar Pradesh',
    speciality: 'Banarasi Brocade Weaving',
    bio: 'A fifth-generation master weaver who has spent 40 years perfecting the art of Banarasi silk brocade. His family\'s looms have produced sarees for royalty and celebrities alike.',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=90',
    rating: 4.9,
    years_experience: 40,
  },
  {
    id: '2',
    name: 'Lakshmi Devi',
    region: 'Kanchipuram, Tamil Nadu',
    speciality: 'Kanjivaram Silk Weaving',
    bio: 'Known for her signature temple border designs, Lakshmi Devi has been weaving Kanjivaram silk sarees since the age of 12. Her work has been exhibited at the Victoria & Albert Museum.',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=90',
    rating: 5.0,
    years_experience: 35,
  },
  {
    id: '3',
    name: 'Mohan Singh Patel',
    region: 'Chanderi, Madhya Pradesh',
    speciality: 'Chanderi Tissue Weaving',
    bio: 'Mohan Singh has revived endangered weaving techniques of Chanderi, creating gossamer-thin tissue sarees that feel like a second skin. His work blends century-old methods with contemporary aesthetics.',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=90',
    rating: 4.8,
    years_experience: 28,
  },
  {
    id: '4',
    name: 'Fatima Begum',
    region: 'Lucknow, Uttar Pradesh',
    speciality: 'Chikankari Embroidery',
    bio: 'A National Award-winning artisan whose delicate Chikankari embroidery transforms plain fabrics into works of art. Her needle dances between shadow-work and lattice patterns with extraordinary finesse.',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=90',
    rating: 4.9,
    years_experience: 30,
  },
  {
    id: '5',
    name: 'Sanjay Kulkarni',
    region: 'Paithan, Maharashtra',
    speciality: 'Paithani Weaving',
    bio: 'The last in his lineage to practice the ancient Paithani weaving technique using pure gold threads. Each of his creations takes 6–18 months to complete on a traditional pit loom.',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=90',
    rating: 5.0,
    years_experience: 45,
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    city: 'Mumbai',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=90',
    quote: 'The Kanjivaram I ordered for my wedding was nothing short of breathtaking. The gold zari work was impeccable, and the silk quality was beyond anything I\'ve seen. MIRA turned my bridal dream into reality.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Ananya Krishnan',
    city: 'Chennai',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=90',
    quote: 'I\'ve been collecting sarees for 20 years, and MIRA\'s Banarasi collection is truly exceptional. The craftsmanship, the attention to detail in every thread — it\'s luxury you can feel.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Deepa Malhotra',
    city: 'Delhi',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=90',
    quote: 'The customization service was extraordinary. They matched the exact shade of emerald I wanted and added personal motifs that tell our family\'s story. A masterpiece I\'ll pass down for generations.',
    rating: 5,
  },
]

export const MARQUEE_ITEMS = [
  'Banarasi Silk',
  'Kanjivaram Gold Zari',
  'Chanderi Tissue',
  'Organza Dreams',
  'Paithani Heritage',
  'Free Shipping Above ₹5,000',
  'Handcrafted with Love',
  '28 Years of Trust',
  'Chikankari Art',
  'Limited Edition Drops',
]

export const NAVIGATION_LINKS = [
  { label: 'Collections', href: '/shop' },
  { label: 'Banarasi', href: '/collections/banarasi' },
  { label: 'Kanjivaram', href: '/collections/kanjivaram' },
  { label: 'Chanderi', href: '/collections/chanderi' },
  { label: 'Customize', href: '/customize' },
  { label: 'Our Story', href: '/about' },
]

export const FOOTER_LINKS = {
  collections: [
    { label: 'Banarasi Silk', href: '/collections/banarasi' },
    { label: 'Kanjivaram Silk', href: '/collections/kanjivaram' },
    { label: 'Chanderi', href: '/collections/chanderi' },
    { label: 'Organza', href: '/collections/organza' },
    { label: 'Printed', href: '/collections/printed' },
    { label: 'Bridal Collection', href: '/collections/kanjivaram' },
  ],
  customerCare: [
    { label: 'Track Your Order', href: '/account/orders' },
    { label: 'Shipping & Returns', href: '/about' },
    { label: 'Size Guide', href: '/about' },
    { label: 'Care Instructions', href: '/about' },
    { label: 'FAQs', href: '/about' },
  ],
  connect: [
    { label: 'About Us', href: '/about' },
    { label: 'Contact', href: '/contact' },
    { label: 'Artisan Stories', href: '/about' },
    { label: 'Careers', href: '/about' },
    { label: 'Press', href: '/about' },
  ],
}

export const PRICE_FORMATTER = new Intl.NumberFormat('en-IN', {
  style: 'currency',
  currency: 'INR',
  maximumFractionDigits: 0,
})
